name: Cypress Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  smoke-tests:
    name: Run Smoke Tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        browser: [chrome, firefox, edge]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Trello app dependencies
        run: |
          cd trelloapp
          npm ci

      - name: Start Trello application
        run: npm run trello &
        env:
          CI: true

      - name: Wait for application
        run: npx wait-on http://localhost:3000 --timeout 60000

      - name: Run Cypress smoke tests
        uses: cypress-io/github-action@v6
        with:
          install: false
          browser: ${{ matrix.browser }}
          spec: cypress/e2e/smoke/**/*.cy.ts
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 60
        env:
          CYPRESS_baseUrl: http://localhost:3000

      - name: Upload screenshots on failure
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots-${{ matrix.browser }}
          path: cypress/screenshots
          retention-days: 7

      - name: Upload videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos-${{ matrix.browser }}
          path: cypress/videos
          retention-days: 7

  regression-tests:
    name: Run Regression Tests
    runs-on: ubuntu-latest
    needs: smoke-tests
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Trello app dependencies
        run: |
          cd trelloapp
          npm ci

      - name: Start Trello application
        run: npm run trello &
        env:
          CI: true

      - name: Wait for application
        run: npx wait-on http://localhost:3000 --timeout 60000

      - name: Run Cypress regression tests
        uses: cypress-io/github-action@v6
        with:
          install: false
          browser: chrome
          spec: cypress/e2e/regression/**/*.cy.ts
          wait-on: 'http://localhost:3000'
        env:
          CYPRESS_baseUrl: http://localhost:3000

      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-regression-artifacts
          path: |
            cypress/screenshots
            cypress/videos
          retention-days: 7

  test-report:
    name: Generate Test Report
    runs-on: ubuntu-latest
    needs: [smoke-tests]
    if: always()

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: List artifacts
        run: ls -R artifacts

      - name: Test Summary
        run: echo "Tests completed. Check artifacts for results."
