name: Docker E2E Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  # ----------------------------------------------------------------
  # JOB 1: Run Smoke Tests across multiple browsers
  # ----------------------------------------------------------------
  smoke_tests:
    name: Smoke Tests (${{ matrix.browser }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: [chrome, firefox, edge]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # This step caches the Docker layers to speed up subsequent builds.
      # The cache is scoped to the branch, so PRs get fresh caches but
      # subsequent pushes to the same branch are much faster.
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('package-lock.json', 'trelloapp/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and load Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true # Load the image into the local Docker daemon
          tags: trello-app:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      # This handles the case where the cache doesn't exist on the first run
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Start Trello app container
        run: |
          docker run \
            -d \
            --name trello-app \
            -p 3000:3000 \
            trello-app:latest

      - name: Wait for app and check logs
        run: |
          echo "Waiting for app to start..."
          sleep 10
          echo "=== Docker container status ==="
          docker ps -a | grep trello-app
          echo "=== Docker logs ==="
          docker logs trello-app
          echo "=== Checking if port 3000 is listening ==="
          docker exec trello-app ss -tulpn | grep 3000 || echo "Port 3000 not listening yet"

      # The Cypress action has a built-in wait-on feature that is more robust.
      - name: Run Cypress smoke tests
        uses: cypress-io/github-action@v6
        with:
          browser: ${{ matrix.browser }}
          spec: cypress/e2e/smoke/**/*.cy.ts
          # Wait for the app to be responsive before running tests
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120 # Wait for up to 2 minutes
        env:
          # Point Cypress to the Dockerized app
          CYPRESS_baseUrl: http://localhost:3000

      - name: Upload screenshots on failure
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: smoke-screenshots-${{ matrix.browser }}
          path: cypress/screenshots
          retention-days: 7

      - name: Upload videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: smoke-videos-${{ matrix.browser }}
          path: cypress/videos
          retention-days: 7

      - name: Merge Mochawesome reports
        if: always()
        run: npm run report:merge
        continue-on-error: true

      - name: Generate Mochawesome HTML report
        if: always()
        run: npm run report:generate
        continue-on-error: true

      - name: Upload Mochawesome report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: smoke-test-report-${{ matrix.browser }}
          path: cypress/reports/mochawesome
          retention-days: 30

      # This step will run even if the Cypress tests fail, ensuring cleanup.
      - name: Cleanup Trello app container
        if: always()
        run: |
          echo "Stopping and removing the Docker container..."
          docker logs trello-app || true
          docker stop trello-app || true
          docker rm trello-app || true

  # ----------------------------------------------------------------
  # JOB 2: Run Regression Tests on Chrome
  # ----------------------------------------------------------------
  regression_tests:
    name: Regression Tests (Chrome)
    runs-on: ubuntu-latest
    needs: smoke_tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('package-lock.json', 'trelloapp/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and load Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: trello-app:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Start Trello app container
        run: |
          docker run \
            -d \
            --name trello-app \
            -p 3000:3000 \
            trello-app:latest

      - name: Run Cypress regression tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          spec: cypress/e2e/regression/**/*.cy.ts
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
        env:
          CYPRESS_baseUrl: http://localhost:3000

      - name: Upload screenshots on failure
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: regression-screenshots
          path: cypress/screenshots
          retention-days: 7

      - name: Upload videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: regression-videos
          path: cypress/videos
          retention-days: 7

      - name: Merge Mochawesome reports
        if: always()
        run: npm run report:merge
        continue-on-error: true

      - name: Generate Mochawesome HTML report
        if: always()
        run: npm run report:generate
        continue-on-error: true

      - name: Upload Mochawesome report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: regression-test-report
          path: cypress/reports/mochawesome
          retention-days: 30

      - name: Cleanup Trello app container
        if: always()
        run: |
          echo "Stopping and removing the Docker container..."
          docker logs trello-app || true
          docker stop trello-app || true
          docker rm trello-app || true

  # ----------------------------------------------------------------
  # JOB 3: Run Authentication Tests on Chrome
  # ----------------------------------------------------------------
  auth_tests:
    name: Authentication Tests (Chrome)
    runs-on: ubuntu-latest
    needs: smoke_tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('package-lock.json', 'trelloapp/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and load Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: trello-app:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Start Trello app container
        run: |
          docker run \
            -d \
            --name trello-app \
            -p 3000:3000 \
            trello-app:latest

      - name: Run Cypress authentication tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          spec: cypress/e2e/auth/**/*.cy.ts
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
        env:
          CYPRESS_baseUrl: http://localhost:3000

      - name: Upload screenshots on failure
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: auth-screenshots
          path: cypress/screenshots
          retention-days: 7

      - name: Upload videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: auth-videos
          path: cypress/videos
          retention-days: 7

      - name: Merge Mochawesome reports
        if: always()
        run: npm run report:merge
        continue-on-error: true

      - name: Generate Mochawesome HTML report
        if: always()
        run: npm run report:generate
        continue-on-error: true

      - name: Upload Mochawesome report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: auth-test-report
          path: cypress/reports/mochawesome
          retention-days: 30

      - name: Cleanup Trello app container
        if: always()
        run: |
          echo "Stopping and removing the Docker container..."
          docker logs trello-app || true
          docker stop trello-app || true
          docker rm trello-app || true
  # ----------------------------------------------------------------
  # JOB 4: Run Accessibility Tests on Chrome
  # ----------------------------------------------------------------
  accessibility_tests:
    name: Accessibility Tests (Chrome)
    runs-on: ubuntu-latest
    needs: smoke_tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('package-lock.json', 'trelloapp/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and load Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: trello-app:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Start Trello app container
        run: |
          docker run \
            -d \
            --name trello-app \
            -p 3000:3000 \
            trello-app:latest

      - name: Run Cypress accessibility tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          spec: cypress/e2e/accessibility/**/*.cy.ts
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
        env:
          CYPRESS_baseUrl: http://localhost:3000

      - name: Upload screenshots on failure
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: accessibility-screenshots
          path: cypress/screenshots
          retention-days: 7

      - name: Upload videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: accessibility-videos
          path: cypress/videos
          retention-days: 7

      - name: Merge Mochawesome reports
        if: always()
        run: npm run report:merge
        continue-on-error: true

      - name: Generate Mochawesome HTML report
        if: always()
        run: npm run report:generate
        continue-on-error: true

      - name: Upload Mochawesome report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: accessibility-test-report
          path: cypress/reports/mochawesome
          retention-days: 30

      - name: Cleanup Trello app container
        if: always()
        run: |
          echo "Stopping and removing the Docker container..."
          docker logs trello-app || true
          docker stop trello-app || true
          docker rm trello-app || true

  # ----------------------------------------------------------------
  # JOB 5: Run Visual Tests with Applitools
  # ----------------------------------------------------------------
  visual_tests:
    name: Visual Tests (Applitools)
    runs-on: ubuntu-latest
    needs: smoke_tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('package-lock.json', 'trelloapp/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and load Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: trello-app:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Start Trello app container
        run: |
          docker run \
            -d \
            --name trello-app \
            -p 3000:3000 \
            trello-app:latest

      - name: Run Cypress visual tests with Applitools
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          spec: cypress/e2e/visual/**/*.cy.ts
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
        env:
          CYPRESS_baseUrl: http://localhost:3000
          APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}

      - name: Upload screenshots on failure
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: visual-screenshots
          path: cypress/screenshots
          retention-days: 7

      - name: Upload videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: visual-videos
          path: cypress/videos
          retention-days: 7

      - name: Merge Mochawesome reports
        if: always()
        run: npm run report:merge
        continue-on-error: true

      - name: Generate Mochawesome HTML report
        if: always()
        run: npm run report:generate
        continue-on-error: true

      - name: Upload Mochawesome report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: visual-test-report
          path: cypress/reports/mochawesome
          retention-days: 30

      - name: Cleanup Trello app container
        if: always()
        run: |
          echo "Stopping and removing the Docker container..."
          docker logs trello-app || true
          docker stop trello-app || true
          docker rm trello-app || true

