name: Visual Regression Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  visual-tests:
    name: Applitools Visual Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Trello app dependencies
        run: |
          cd trelloapp
          npm ci

      - name: Start Trello application
        run: npm run trello &
        env:
          CI: true

      - name: Wait for application
        run: npx wait-on http://localhost:3000 --timeout 60000

      - name: Run visual regression tests
        uses: cypress-io/github-action@v6
        with:
          install: false
          browser: chrome
          spec: cypress/e2e/visual/**/*.cy.ts
          wait-on: 'http://localhost:3000'
        env:
          APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
          CYPRESS_baseUrl: http://localhost:3000

      - name: Upload results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: visual-test-results
          path: cypress/videos
          retention-days: 7
